### ISSUE TITLE
Large Scale Maps feasable?

### ISSUE THREAD

**Issue by petergerten** [HKPolyU-UAV/MLMapping#1]
Would this mapping method work with large scale maps?
E.g. I want to import a 1000m * 200m * 100m maps with several buildings (based on existing photogrammetry model) and the use the mapping system to update it with realtime observed data?

**Comment by Ttoto** [comment]
The short answer is 'NO'
As this mapping kit is designed for the UAV/mobile robot navigation applications (typical scope of such applications is 50m*50m*10m), we never test in such a large scale environment (1000m*200m*100m). 
We do implement the dynamic memory management, which can balance the overhead of memory and map scale and achieve large scale mapping. U can used this feature is ur own projects.
