### ISSUE TITLE
A mistype in README.md

### ISSUE THREAD

**Issue by bigbellmercy** [HKPolyU-UAV/MLMapping#2]
Hello, Thank you for contribution!

I found a small mistype in README.md.

Wrong:
cd catkin_ws/src/**glmapping**/3rdPartLib/
./install3rdPartLib.sh

Correct:
cd catkin_ws/src/**MLMapping**/3rdPartLib/
./install3rdPartLib.sh

**Comment by Ttoto** [comment]
Thank you for your feedback! It is a mistake, and I have corrected it.

**Comment by bigbellmercy** [comment]
Thank you.
