### ISSUE TITLE
Build error 'fatal error: nav_msgs/Odometry.h: No such file or directory'

### ISSUE THREAD

**Issue by bigbellmercy** [HKPolyU-UAV/MLMapping#3]
Hi~ When `catkin_make` is commanded for compile as the README.md, The following build error (and similar errors) happens:

```
/home/user/catkin_ws/src/MLMapping/src/independent_modules/repub_rec.cpp:6:10: fatal error: nav_msgs/Odometry.h: No such file or directory
 #include "nav_msgs/Odometry.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
```
In file included from /home/user/catkin_ws/src/MLMapping/src/node_visualization.cpp:7:0:
/home/user/catkin_ws/src/MLMapping/src/rviz_vis.h:8:10: fatal error: visualization_msgs/Marker.h: No such file or directory
 #include <visualization_msgs/Marker.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
...and so on...

Build environment: Ubuntu 18.04, ROS Melodic

**Comment by bigbellmercy** [comment]
In my `catkin_ws/common_msgs/nav_msgs` folder, any header file, including `Odometry.h`, does not exist.
As I go to the GitHub for `common_msgs/nav_msgs` no header file is there too.

**Comment by bigbellmercy** [comment]
I've found a solution for it.

In the CMakeList.txt of MLMapping folder, I added the following sentences:
1. In `find_package()`, `nav_msgs`, `visualization_msgs` and `pcl_conversions` were added.
2. In `generate_messages()`, `nav_msgs` and `visualization_msgs` were added.

After that, such errors disappeared and its build succeeded.

**Comment by bigbellmercy** [comment]
It's nice VIO!
When I used the provided dataset the 'Large Scale Mapping Dataset', its 3D maps are drawn nicely.

**Comment by Ttoto** [comment]
Thank you for your feedback! I have updated the CMakeLists.txt.

**Comment by bigbellmercy** [comment]
Thanks. It's built and run well after the change. You may close this issue.
