### ISSUE TITLE
Failed to load nodelet [/glmapping_GlobalMapNodeletClass_loader] of type [glmapping/GlobalMapNodeletClass]

### ISSUE THREAD

**Issue by ashd7** [HKPolyU-UAV/MLMapping#4]
After running E2ES and FLVIS, when i ran roslaunch e2es glmapping.launch. Its showing the following error. I tried using both glmapping and mlmapping, same error for both. In Rviz, in glmapping subsection in Displays, it shows no map recieved in 2D_GridMap. Pic uploaded.

ERROR - Failed to load nodelet [/glmapping_GlobalMapNodeletClass_loader] of type [glmapping/GlobalMapNodeletClass] even after refreshing the cache: According to the loaded plugin descriptions the class glmapping/GlobalMapNodeletClass with base class type nodelet::Nodelet does not exist. Declared types are  SlamGMappingNodelet flvis/LocalMapNodeletClass flvis/LoopClosingNodeletClass flvis/TrackingNodeletClass image_view/disparity image_view/image mlmapping/AwarenessMapNodeletClass mlmapping/LocalMapNodeletClass octomap_color_server/OctomapServerNodelet octomap_server/OctomapServerNodelet pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid
[ERROR] [1627301040.355256204]: The error before refreshing the cache was: According to the loaded plugin descriptions the class glmapping/GlobalMapNodeletClass with base class type nodelet::Nodelet does not exist. Declared types are  SlamGMappingNodelet flvis/LocalMapNodeletClass flvis/LoopClosingNodeletClass flvis/TrackingNodeletClass image_view/disparity image_view/image mlmapping/AwarenessMapNodeletClass mlmapping/LocalMapNodeletClass octomap_color_server/OctomapServerNodelet octomap_server/OctomapServerNodelet pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid
[FATAL] [1627301040.355431370]: Failed to load nodelet '/glmapping_GlobalMapNodeletClass_loader` of type `glmapping/GlobalMapNodeletClass` to manager `glmapping_nodelet_manager'
[glmapping_GlobalMapNodeletClass_loader-3] process has died [pid 8722, exit code 255, cmd bash -c sleep 1; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load glmapping/GlobalMapNodeletClass glmapping_nodelet_manager __name:=glmapping_GlobalMapNodeletClass_loader __log:=/home/ashd/.ros/log/118e0b9e-ee03-11eb-923a-30d16befe015/glmapping_GlobalMapNodeletClass_loader-3.log].
log file: /home/ashd/.ros/log/118e0b9e-ee03-11eb-923a-30d16befe015/glmapping_GlobalMapNodeletClass_loader-3*.log
![Screenshot from 2021-07-26 17-18-30](https://user-images.githubusercontent.com/87776551/126986416-f8e55716-884a-4e47-a9d0-141fe6a43f7f.png)

**Comment by Ttoto** [comment]
I am sorry for the late reply, I just notice this issue. 
Currently, the E2ES support glmapping only. I will add the support of mlmapping by this Fri.

**Comment by Ttoto** [comment]
I believe I reproduce this issue. Please make sure that you download the mapping kit from [https://github.com/HKPolyU-UAV/glmapping](https://github.com/HKPolyU-UAV/glmapping) instead of this repo.
So that you can use full navigation stack (flvis+glmapping+fuxi-planner)
The new navigation stack is coming soon( flvis+MLMapping(this repo)+planner(the paper is under review))

**Comment by ashd7** [comment]
Its showing the same error with glmapping kit too. Also when i try roslaunch glmapping mlmapping_bag_sim.launch it shows RLException: [mlmapping_bag_sim.launch] is neither a launch file in package [glmapping] nor is [glmapping] a launch file name. Even after i source the setup.bash file.

**Comment by Ttoto** [comment]
> Its showing the same error with glmapping kit too. Also when i try roslaunch glmapping mlmapping_bag_sim.launch it shows RLException: [mlmapping_bag_sim.launch] is neither a launch file in package [glmapping] nor is [glmapping] a launch file name. Even after i source the setup.bash file.

There is no mlmapping_bag_sim.launch in glmapping package. Please make sure the glmapping is checkout from [https://github.com/**HKPolyU-UAV**/glmapping](https://github.com/HKPolyU-UAV/glmapping)

**Comment by Ttoto** [comment]
> After running E2ES and FLVIS, when i ran roslaunch e2es glmapping.launch. Its showing the following error. I tried using both glmapping and mlmapping, same error for both. In Rviz, in glmapping subsection in Displays, it shows no map recieved in 2D_GridMap. Pic uploaded.
> 
> ERROR - Failed to load nodelet [/glmapping_GlobalMapNodeletClass_loader] of type [glmapping/GlobalMapNodeletClass] even after refreshing the cache: According to the loaded plugin descriptions the class glmapping/GlobalMapNodeletClass with base class type nodelet::Nodelet does not exist. Declared types are SlamGMappingNodelet flvis/LocalMapNodeletClass flvis/LoopClosingNodeletClass flvis/TrackingNodeletClass image_view/disparity image_view/image mlmapping/AwarenessMapNodeletClass mlmapping/LocalMapNodeletClass octomap_color_server/OctomapServerNodelet octomap_server/OctomapServerNodelet pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid
> [ERROR] [1627301040.355256204]: The error before refreshing the cache was: According to the loaded plugin descriptions the class glmapping/GlobalMapNodeletClass with base class type nodelet::Nodelet does not exist. Declared types are SlamGMappingNodelet flvis/LocalMapNodeletClass flvis/LoopClosingNodeletClass flvis/TrackingNodeletClass image_view/disparity image_view/image mlmapping/AwarenessMapNodeletClass mlmapping/LocalMapNodeletClass octomap_color_server/OctomapServerNodelet octomap_server/OctomapServerNodelet pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid
> [FATAL] [1627301040.355431370]: Failed to load nodelet '/glmapping_GlobalMapNodeletClass_loader`of type`glmapping/GlobalMapNodeletClass`to manager`glmapping_nodelet_manager'
> [glmapping_GlobalMapNodeletClass_loader-3] process has died [pid 8722, exit code 255, cmd bash -c sleep 1; $0 $@ /opt/ros/melodic/lib/nodelet/nodelet load glmapping/GlobalMapNodeletClass glmapping_nodelet_manager __name:=glmapping_GlobalMapNodeletClass_loader __log:=/home/ashd/.ros/log/118e0b9e-ee03-11eb-923a-30d16befe015/glmapping_GlobalMapNodeletClass_loader-3.log].
> log file: /home/ashd/.ros/log/118e0b9e-ee03-11eb-923a-30d16befe015/glmapping_GlobalMapNodeletClass_loader-3*.log
> ![Screenshot from 2021-07-26 17-18-30](https://user-images.githubusercontent.com/87776551/126986416-f8e55716-884a-4e47-a9d0-141fe6a43f7f.png)

Please have a check of the output prior to the [FATAL] section. If there is some error report?
In one of my computer(Ubuntu 20.04+ROS Noetic) there is an error 
`libglmapping.so: undefined symbol: _ZN6Sophus3SE3C1Ev`
If so, you can add 
`set(Sophus_LIBRARIES libSophus.so)`
into the CMakeLists.txt (after `find_package (Sophus REQUIRED)` )

**Comment by ashd7** [comment]
So this issue was solved. the problem was the repo to be cloned given in the glmapping README was git clone https://github.com/Ttoto/glmapping.git, it worked when i cloned this https://github.com/HKPolyU-UAV/glmapping.git. Thanks for the help!
Also im facing another issue while using Fuxi planner.
When i launch fuxi-planner after glmapping this shows up and 2D Nav Goal does not work. 
[program_flyonce-4] process has died [pid 5820, exit code 1, cmd bash -c sleep 5.0; $0 $@ /home/ashd/slam_ws/src/fuxi-planner/scripts/program_flyonce.py __name:=program_flyonce __log:=/home/ashd/.ros/log/f3b72d78-feb3-11eb-90e1-30d16befe015/program_flyonce-4.log].
log file: /home/ashd/.ros/log/f3b72d78-feb3-11eb-90e1-30d16befe015/program_flyonce-4*.log
Thanks in advance!

**Comment by ashd7** [comment]
So this issue was solved. the problem was the repo to be cloned given in the glmapping README was git clone https://github.com/Ttoto/glmapping.git, it worked when i cloned this https://github.com/HKPolyU-UAV/glmapping.git. But both repos seem to be the same. Idk what i cloned earlier:) Thanks for the help!

Also im facing another issue while using Fuxi planner.
When i launch fuxi-planner after glmapping, this shows up, 2D Nav Goal works and even the path (white line with yellow sphere appears) is planned but the drone remains stationary.

ERROR: [program_flyonce-4] process has died [pid 11132, exit code 1, cmd bash -c sleep 5.0; $0 $@ /home/ashd/slam_ws/src/fuxi-planner/scripts/program_flyonce.py __name:=program_flyonce __log:=/home/ashd/.ros/log/7e316b08-febe-11eb-90e1-30d16befe015/program_flyonce-4.log].
log file: /home/ashd/.ros/log/7e316b08-febe-11eb-90e1-30d16befe015/program_flyonce-4*.log

ps: ./st_start.sh demo shows the same error but it seems to works fine.

Thanks in advance!

**Comment by Ttoto** [comment]
Thank you for your feedback and I have correct the hyperlink in the README file.
Happy to help. I will close this issue if there is no other question.

**Comment by AshwinDisa** [comment]
Yes sure. Thanks for the help!
